@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

Package Client{

}

Package Entity{
class HouseHold
class User
class MainMenu
}

Package Utility{
}

'Label on relations

HouseHold "1" *-- User: has "*"
@enduml